day3/crud_demo/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "tasks#index"

  resources :users
  resources :tasks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

day3/crud_demo/app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user.nil?
      guest_user
    else
      signed_in_user(user)
    end
  end

  def guest_user
    can :index, Task
    can :read, Task
  end

  def signed_in_user(user)
    guest_user
    can :create, Task
    can [:edit, :destroy], Task, user_id: user.id
  end
end

day3/crud_demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

day3/crud_demo/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :task
  belongs_to :user
  accepts_nested_attributes_for :user
end

day3/crud_demo/app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_tasks
  has_many :tasks, through: :tag_tasks
end

day3/crud_demo/app/models/tag_task.rb
class TagTask < ApplicationRecord
  belongs_to :tag
  belongs_to :task
end

day3/crud_demo/app/models/task.rb
class Task < ApplicationRecord
  belongs_to :user

  has_many :tag_tasks
  has_many :tags, through: :tag_tasks

  has_many :comments

  scope :completed, -> { where(completed: true )}
  scope :in_progress, -> { where(completed: false )}
  scope :with_username, -> { joins(:user).select('tasks.*, users.name as user_name')}

  after_create :log_new_task

  scope :with_comments_count, -> do
    left_joins(:comments)
        .select('tasks.*, count(comments.id) as comments_count')
        .group('tasks.id')
  end

  # allow updating this task's comments
  accepts_nested_attributes_for :comments, allow_destroy: true


  validate :no_bad_words_in_description

  validates :priority, numericality: {
      greater_than_or_equal_to: 0,
      less_than_or_equal_to: 5,
  }

  def no_bad_words_in_description
    if description.include?('python')
      errors.add(:base, "Sorry python is not allowed")
    end
  end

  def comments_with_usernames
    comments.joins(:user).select('comments.*, users.name as username')
  end

  def log_new_task
    TasklogJob.perform_later(self)
  end
end

day3/crud_demo/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tasks
end

day3/crud_demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied, with: :redirect_to_login

  def redirect_to_login(exception)
    if current_user.nil?
      redirect_to(new_user_session_path, notice: 'Please sign in to continue')
    else
      raise exception
    end
  end
end

day3/crud_demo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  # GET /tasks
  # GET /tasks.json
  def index
    authorize! :index, Task

    filter = params[:completed]
    @tasks = if filter.nil?
               Task.all
             elsif filter == "0"
               Task.in_progress
             elsif filter == "1"
               Task.completed
             end

    @tasks = @tasks.with_username.with_comments_count
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    authorize! :show, @task
    @comments = @task.comments_with_usernames
  end

  # GET /tasks/new
  def new
    authorize! :create, Task
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
    authorize! :edit, @task
  end

  # POST /tasks
  # POST /tasks.json
  def create
    authorize! :create, Task
    @task = Task.new(task_params.merge(user: current_user))

    respond_to do |format|
      if @task.save
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    authorize! :edit, @task
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    authorize! :destroy, @task
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(
          :owner,
          :description,
          :priority,
          :completed,
          comments_attributes: [
              :id, :_destroy, :text
          ]
      )
    end
end

day3/crud_demo/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :favorite_color)
    end
end

day3/crud_demo/app/helpers/application_helper.rb
module ApplicationHelper
end

day3/crud_demo/app/helpers/tasks_helper.rb
module TasksHelper
end

day3/crud_demo/app/helpers/users_helper.rb
module UsersHelper
end

day3/crud_demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CrudDemo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <% if user_signed_in? %>
    <p>Welcome <%= current_user.email %></p>
    <%= link_to('Logout', destroy_user_session_path, method: :delete) %>
  <% else %>
    <%= link_to 'Sign In', new_user_session_path %>
  <% end %>

    <%= yield %>
  </body>
</html>

day3/crud_demo/app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :priority %>
    <%= form.text_field :priority %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>

  <h2>Comments</h2>

  <% task.comments.each do |comment| %>
    <%= form.fields_for(:comments, comment) do |comment_form| %>
      <div class="field">
        <%= comment_form.label :text %>
        <%= comment_form.text_field :text %>
      </div>
    <% end %>
  <%  end %>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

day3/crud_demo/app/views/tasks/_task_comment.html.erb
<li>
  <b><%= comment.username %></b>: <%= comment.text %>
  <%= link_to 'Delete', '...' %>
</li>

day3/crud_demo/app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

day3/crud_demo/app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Owner</th>
      <th>Description</th>
      <th>Priority</th>
      <th>Completed</th>
      <th>Comments Count</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= link_to 'All Tasks', tasks_path, 'data-test-id': 'all-tasks-btn' %>
  <%= link_to 'Active Tasks', tasks_path(completed: 0) %>
  <%= link_to 'Completed Tasks', tasks_path(completed: 1) %>

  <tbody>
    <% @tasks.each do |task| %>
      <tr class="task-line">
        <td><%= task.user_name %></td>
        <td><%= task.description %></td>
        <td><%= task.priority %></td>
        <td><%= task.completed %></td>
        <td><%= task.comments_count %></td>
        <td><%= link_to task.id, task %></td>
        <% if can? :edit, task %>
          <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <% end  %>
        <% if can? :destroy, task %>
          <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

day3/crud_demo/app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

day3/crud_demo/app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @task.priority %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @task.completed %>
</p>

<h2>Comments</h2>
<ul>
  <%= render partial: 'task_comment',
             collection: @comments,
             as: :comment
  %>
</ul>

<% if can? :edit, @task %>
  <%= link_to 'Edit', edit_task_path(@task) %> |
<% end %>
<%= link_to 'Back', tasks_path %>

day3/crud_demo/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :favorite_color %>
    <%= form.text_field :favorite_color %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

day3/crud_demo/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

day3/crud_demo/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Favorite color</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.favorite_color %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

day3/crud_demo/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

day3/crud_demo/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Favorite color:</strong>
  <%= @user.favorite_color %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>